#include<stdio.h>
#include<math.h>
main()
{
	int n,s[9],i,j,temp,k,count=0,flag=0;
	int x,y,z;
	int xb,xs,xg,yb,ys,yg,zb,zs,zg;
	scanf("%d",&n);
	if(n>3||n<=0)
	{
		printf("0,0,0\n");
	}
	else
	{
		if(n==1)
		{
			for(x=100;x<200;x++)
		    {
		    	y=2*x;
		    	z=3*x;
			    xg=x%10;xs=((x-xg)/10)%10;xb=((x-10*xs-xg)/100)%10;
			    yg=y%10;ys=((y-yg)/10)%10;yb=((y-10*ys-yg)/100)%10;
			    zg=z%10;zs=((z-zg)/10)%10;zb=((z-10*zs-zg)/100)%10;
			    s[0]=xg;s[1]=xs;s[2]=xb;
			    s[3]=yg;s[4]=ys;s[5]=yb;
			    s[6]=zg;s[7]=zs;s[8]=zb;
			    for(i=0;i<9;i++)
			    {
			    	for(j=0;j<9;j++)
			    	{
			    		if(s[j]>s[j+1])
			    		{
			    			temp=s[j];
			    			s[j]=s[j+1];
			    			s[j+1]=temp;
						}
					}
				}
				for(k=0;k<9;k++)
				{
					if(s[k]==(s[1+k]-1))
					{
						count++;
					}
				}
				if(count==8)
				{
					printf("%d,%d,%d\n",x,y,z);
					flag=1;
				}
				count=0;
	    	}
		}
		else if(n==3)
		{
			for(x=300;x<=333;x++)
		    {
		    	y=2*x;
		    	z=3*x;
			    xg=x%10;xs=((x-xg)/10)%10;xb=((x-10*xs-xg)/100)%10;
			    yg=y%10;ys=((y-yg)/10)%10;yb=((y-10*ys-yg)/100)%10;
			    zg=z%10;zs=((z-zg)/10)%10;zb=((z-10*zs-zg)/100)%10;
			    s[0]=xg;s[1]=xs;s[2]=xb;
			    s[3]=yg;s[4]=ys;s[5]=yb;
			    s[6]=zg;s[7]=zs;s[8]=zb;
			    for(i=0;i<9;i++)
			    {
			    	for(j=0;j<9;j++)
			    	{
			    		if(s[j]>s[j+1])
			    		{
			    			temp=s[j];
			    			s[j]=s[j+1];
			    			s[j+1]=temp;
						}
					}
				}
				for(k=0;k<9;k++)
				{
					if(s[k]==(s[1+k]-1))
					{
						count++;
					}
				}
				if(count==8)
				{
					printf("%d,%d,%d\n",x,y,z);
					flag=1;
				}
				count=0;
	    	}
		}
		else if(n==2)
		{
			for(x=200;x<=300;x++)
		    {
		    	y=2*x;
		    	z=3*x;
			    xg=x%10;xs=((x-xg)/10)%10;xb=((x-10*xs-xg)/100)%10;
			    yg=y%10;ys=((y-yg)/10)%10;yb=((y-10*ys-yg)/100)%10;
			    zg=z%10;zs=((z-zg)/10)%10;zb=((z-10*zs-zg)/100)%10;
			    s[0]=xg;s[1]=xs;s[2]=xb;
			    s[3]=yg;s[4]=ys;s[5]=yb;
			    s[6]=zg;s[7]=zs;s[8]=zb;
			    for(i=0;i<9;i++)
			    {
			    	for(j=0;j<9;j++)
			    	{
			    		if(s[j]>s[j+1])
			    		{
			    			temp=s[j];
			    			s[j]=s[j+1];
			    			s[j+1]=temp;
						}
					}
				}
				for(k=0;k<9;k++)
				{
					if(s[k]==(s[1+k]-1))
					{
						count++;
					}
				}
				if(count==8)
				{
					printf("%d,%d,%d\n",x,y,z);
					flag=1;
				}
				count=0;
	    	}
		}
		if(flag==0)
	    {
		    printf("0,0,0\n");
     	}
	}
}